# Basic
title: å¼ åˆšé‡‘
subtitle: ä¸ªäººç«™
description: zgangjin
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: leopardpan
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS / æœºå™¨å­¦ä¹ 
url: "http://072322.top"

# Comment
comment:
    # disqus: leopard
    duoshuo: leopard 

# Social
social:
    weibo: 729777679 
    github: zgangjin
    # twitter: 
    mail: 729777679@qq.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421xt  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-84134159-3xt   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹
# Miscellaneous
google_analytics: ''
favicon: img/headimg_dl.jpg

#ä½ çš„å¤´åƒurl
avatar:img/headimg_dl.jpg

permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  tagcloud: 'æ ‡ç­¾'
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæˆ‘'
   

# å‹æƒ…é“¾æ¥    
friends:
  å‹æƒ…é“¾æ¥1: http://shenqianqian.com
 
# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

aboutme: ä¸è¦å› ä¸ºè·¯é€”é¥è¿œå°±å¿˜è®°ä¸ºä»€ä¹ˆè€Œå‡ºå‘
